steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/cashflow-worker', '-f', 'deploy/Dockerfile.worker', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/cashflow-worker' ]
images:
  - 'gcr.io/$PROJECT_ID/cashflow-worker'

