steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/cashflow-api', '-f', 'deploy/Dockerfile', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/cashflow-api' ]
images:
  - 'gcr.io/$PROJECT_ID/cashflow-api'

